---
# tasks file for roles/golang
- hosts: localhost
  sudo: yes
  roles:
  #- meatballhat.minecraft
  - { role: joshualund.golang, tags: ['golang'] }
  vars:
    golang_version: 1.4.2
    go_tarball: "go1.4.2.linux-amd64.tar.gz"
    go_tarball_checksum: "141b8345932641483c2437bdbd65488a269282ac85f91170805c273f03dd223b"
    go_version_target: "go version go1.4.2 linux/amd64"
  tasks:
  - name: install golang deps
    sudo: yes
    apt:
      name="{{ item }}"
      state=present
    with_items:
    - mercurial
  - name: install golang packages
    sudo: no
    shell: "go get -v -u {{ item }}"
    with_items:
    - golang.org/x/tools/cmd/goimports
    - github.com/monochromegane/the_platinum_searcher/...
    - github.com/tools/godep
    - github.com/astaxie/beego
    - github.com/spf13/hugo
