---
# tasks file for roles/golang
- hosts: localhost
  tasks:
  - name: install golang role
    shell: ansible-galaxy install joshualund.golang --force

- hosts: localhost
  sudo: yes
  roles:
  #- meatballhat.minecraft
  - { role: joshualund.golang, tags: ['golang'] }
  vars:
    golang_version: 1.5.1
    go_tarball: "go1.5.1.linux-amd64.tar.gz"
    go_tarball_checksum: "2593132ca490b9ee17509d65ee2cd078441ff544899f6afb97a03d08c25524e7"
    go_version_target: "go version go1.5.1 linux/amd64"
  tasks:
  - name: install golang deps
    sudo: yes
    apt:
      name="{{ item }}"
      state=present
    with_items:
    - mercurial
  - name: install golang packages
    sudo: no
    shell: "go get -v -u {{ item }}"
    with_items:
    - golang.org/x/tools/cmd/goimports
    - github.com/monochromegane/the_platinum_searcher/...
    - github.com/tools/godep
    - github.com/astaxie/beego
    - github.com/spf13/hugo
